### ISSUE TITLE
Use states to show field only if needed (for Webform component)

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/select_or_other#2]
![Screen Shot 2020-10-20 at 12 39 45 PM](https://user-images.githubusercontent.com/871421/96623826-8bed9480-12d1-11eb-9120-902efa79af68.jpg)

The "Text for 'Other...' option" field could be hidden with `#states` unless the checkbox above it is selected.

**Comment by herbdool** [comment]
This appears to be a Webform-specific issue.

**Comment by herbdool** [comment]
And actually the code is in the Webform module not here (confusingly). I just tested it and it is working for me. I don't see a change in the code recently according to git blame so I assume this has been working for awhile.
