### ISSUE TITLE
hook_update_N and hook_update_last_removed

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/select_or_other#4]
> function select_or_other_update_7201() {

It looks like `hook_update_N` and `hook_update_last_removed` need to be adjusted/added in the install file.

**Comment by laryn** [comment]
I submitted a PR here.

**Comment by olafgrabienski** [comment]
@laryn I have a D7 site which uses *Select or Other*, and I'm preparing that site for an upgrade to Backdrop. Do you know if this issue here is relevant for the upgrade process?

**Comment by laryn** [comment]
Yes, it is relevant. @herbdool Does this PR look good to you?

**Comment by herbdool** [comment]
Thanks @laryn
